export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_USER_SUCCESS = "GET_LIST_USER_SUCCESS";
export const GET_LIST_USER_FAILED = "GET_LIST_USER_FAILED";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const GET_USER_DETAIL_FAILED = "GET_USER_DETAIL_FAILED";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const ADD_ADDRESS = "ADD_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const ADD_PHONE_NUMBER = "ADD_PHONE_NUMBER";
export const DELETE_PHONE_NUMBER = "DELETE_PHONE_NUMBER";
export const ADD_EMAIL = "ADD_EMAIL";
export const DELETE_EMAIL = "DELETE_EMAIL";

export const SEARCH_USERS = "SEARCH_USERS";

export const LOG_WORK = "LOG_WORK";
export const LOG_WORK_SUCCESS = "LOG_WORK_SUCCESS";
export const LOG_WORK_FAILED = "LOG_WORK_FAILED";

export const DISPLAY_LOG_WORK = "DISPLAY_LOG_WORK";
export const DISPLAY_ADD_USER = "DISPLAY_ADD_USER";
export const DISPLAY_VIEW_USER_DETAIL = "DISPLAY_VIEW_USER_DETAIL";
export const DISPLAY_UPDATE_USER = "DISPLAY_UPDATE_USER";
export const CLOSE_UPDATE_USER = "CLOSE_UPDATE_USER";
export const CLOSE_FORM = "CLOSE_FORM";